### ISSUE TITLE
Versions display fails on Windows

### ISSUE THREAD

**Issue by gfosco** [coreh-deprecated/nide#28] opened 2011-12-29 16:27 UTC
Displayed instead of previous file contents:  <ERROR: Could not load file contents>

The arrows work to switch through the history (the timestamp on top changes) but no old versions are shown.

**Comment by coreh** [comment] 2011-12-31 18:54
Closing this since it's a duplicate of #6.

**Closed as completed by coreh** 2011-12-31 18:54 UTC
Labels: bug, duplicate
